load_module "/usr/lib/nginx/modules/ngx_http_coraza_module.so";

pid /tmp/nginx.pid;

events {}

http {
    server {
        listen 8080;
        server_name localhost;

        # Apply Coraza engine
        coraza on;
        coraza_rules_file /opt/coraza/config/custom-coraza.conf;

        location / {
            # Forward traffic to the vulnerable app
            proxy_pass http://vulnerable-app:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
