load_module "/usr/lib/nginx/modules/ngx_http_coraza_module.so";

pid /tmp/nginx.pid;

events {}

http {
    limit_req_zone $binary_remote_addr zone=per_ip_limit:10m rate=5r/s;
    map $http_user_agent $is_bad_bot {
        default 0;
        ~*(curl|PostmanRuntime|sqlmap|nikto|nmap|dirbuster|masscan) 1;
    }

    server {
        listen 8080;
        server_name localhost;
        limit_req_status 429;

        # Apply Coraza engine
        coraza on;
        coraza_rules_file /opt/coraza/config/custom-coraza.conf;

        location / {
            if ($is_bad_bot) {
                return 403;
            }
            limit_req zone=per_ip_limit burst=10 nodelay;

            # IMPORTANT: Replace <PRIVATE_IP_OF_EC2_B> with the private IP of your asset host (EC2-B)
            # before deployment. Your vulnerable-app listens on host port 3000 on that instance.
            proxy_pass http://<PRIVATE_IP_OF_EC2_B>:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
